//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApiDosyaIslemleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int fileId { get; set; }
        public string fileName { get; set; }
        public string fileUrl { get; set; }
    }
}
